POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video",
    "description": "Primeiro video enviado Node",
    "duration": 180
}

###

GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/0
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Primeiro video enviado e testadoa",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/0